apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-vite-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-vite-app
  template:
    metadata:
      labels:
        app: react-vite-app
    spec:
      containers:
      - name: react-vite-app
        image: harshini123456/devops-app  # <-- Your updated image
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: react-vite-service
spec:
  selector:
    app: react-vite-app
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
